def create_values_to_fill_avivaontario(processed_info):
    return {
        'Holder of Vehicle Portion of the Permit, Surname and Given Names': processed_info['owner_name'],
        'Holder of Vehicle Portion of the Permit, Driver\'s Licence Number or Registrant Identification Number': '',
        'Holder of Vehicle Portion of the Permit, Box Number': processed_info['owner_address'],
        ' Box Number': processed_info['owner_address'],
        'Holder of Vehicle Portion of the Permit, City, Town or Village': processed_info['city'],
        'Holer of Vehicle Portion of the Permit, Postal Code': processed_info['post_code'],
        'Holder of Vehicle Portion of the Permit, Telephone Number': processed_info['phone_number'],
        'Vehicle Insurance, Policy Number': processed_info['policy_number'],
        'Vehicle Insurance, Claim Number': processed_info['claim_number'],
        'Vehicle Insurance, Claim Representative': processed_info['company_name'],
        'Date of Incident, Day': processed_info['date_of_loss'].split('/')[1],
        'Date of Incident, Month': processed_info['date_of_loss'].split('/')[0],
        'Date of Incident, Year': processed_info['date_of_loss'].split('/')[2],
        'Vehicle Identification Number': processed_info['vin'],
        'Vehicle Information, Make': processed_info['make'].split()[0],
        'Vehicle Information, Model': processed_info['make'].split()[1],
        'Vehicle Information, Year': processed_info['model_year'],
        r"\)": 'Auto',
        'Vehicle Information, Colour': processed_info['color'],
        'Vehicle Information, Odometer Reading': processed_info['mileage'],
        'Vehicle Information, Licence Plate': processed_info['license_plate'].split('COLOR')[0],
        'Vehicle Information, Province or State': processed_info['state_prefix'],
        'Appraisal or Inspection Contact Person, Name of Appraiser or Person Who Carried Out Inspection': 'Jason Shufford Jr',
        'Brand Determination, Appraiser\'s Name': 'Jason Shufford Jr',
        'Declaration, Print Name of Person Notifying Registrar': 'Jason Shufford Jr',
        'Declaration, Date': processed_info['formatted_date'],
        'Text22': "Jason Shufford Jr ",
    }